name: C/C++ CI

on:
  [ push ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install glfw
      run: sudo apt-get install libglfw3
    - name: cmake
      run: cmake -H. -Bbuild
    - name: make 
      run: make -C build
    - name: test
      run: cd build && make test
